export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';

export const CREATE_PRODUCT = 'CREATE_PRODUCT';

export const CREATED_PRODUCT = 'CREATED_PRODUCT';

export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';

export const DELETE_PRODUCT = 'DELETE_PRODUCT';

export const DELETED_PRODUCT = 'DELETED_PRODUCT';

export const SINGLE_PRODUCT = 'SINGLE_PRODUCT';

export const LIST_PRODUCTS = 'LIST_PRODUCTS';

export const LEAVING_PRODUCT_SCREEN = 'LEAVING_PRODUCT_SCREEN';
